development:
  adapter: postgresql
  encoding: unicode
  database: marketem_development

test: &test
  adapter: postgresql
  encoding: unicode
  database: marketem_test
  min_messages: warning

cucumber:
  <<: *test