development:
  adapter: postgresql
  encoding: unicode
  database: marketem_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: marketem_test
  pool: 5

cucumber:
  <<: *test
