development:
  adapter: postgresql
  encoding: unicode
  database: marketem_development
  pool: 5
  username:
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: marketem_test
  pool: 5
  username:
  password:

cucumber:
  <<: *test